
spring:
  redis :
    database : 0
    host : 192.168.0.234
    port : 6379
    timeout : 5000
    jedis :
      pool :
        max-active: 200
        max-wait: -1
        max-idle: 10
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    url  : jdbc:mysql://192.168.0.234:3306/dbn?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username : root
    password : 123456